import type { StrongholdCluster } from "./types";

export const STRONGHOLD_CLUSTERS: StrongholdCluster[] = [
  {
    id: "army-base",
    name: "Army base",
    size: 29,
    cost: 24000,
    description: "Quarters for 100 infantry with training, armory, and mess hall.",
    components: [
      { componentId: "barracks", quantity: 10 },
      { componentId: "training-combat", quantity: 5 },
      { componentId: "guard-post", quantity: 2 },
      { componentId: "armory-basic", quantity: 4 },
      { componentId: "dining-hall", quantity: 2 },
      { componentId: "kitchen-basic", quantity: 4 },
      { componentId: "servants-quarters", quantity: 1 },
    ],
    staff: [
      { role: "cook", count: 4 },
      { role: "soldier", count: 100 },
    ],
    monthlyUpkeep: 612,
  },
  {
    id: "banquet-hall",
    name: "Banquet hall",
    size: 18,
    cost: 136200,
    description: "Vast dining hall feeding 150 in a richly appointed atmosphere.",
    components: [
      { componentId: "dining-hall-fancy", quantity: 5 },
      { componentId: "kitchen-fancy", quantity: 5 },
      { componentId: "servants-quarters", quantity: 3 },
    ],
    staff: [
      { role: "cook", count: 10 },
      { role: "servant", count: 5 },
    ],
    monthlyUpkeep: 75,
  },
  {
    id: "cavalry-base",
    name: "Cavalry base",
    size: 45,
    cost: 40000,
    description: "Army base plus stables for a 100-rider cavalry unit.",
    components: [
      { componentId: "barracks", quantity: 10 },
      { componentId: "training-combat", quantity: 5 },
      { componentId: "guard-post", quantity: 2 },
      { componentId: "armory-basic", quantity: 4 },
      { componentId: "dining-hall", quantity: 2 },
      { componentId: "kitchen-basic", quantity: 4 },
      { componentId: "servants-quarters", quantity: 1 },
      { componentId: "stable-basic", quantity: 16 },
    ],
    staff: [
      { role: "cook", count: 4 },
      { role: "groom", count: 16 },
      { role: "soldier", count: 100 },
    ],
    monthlyUpkeep: 684,
  },
  {
    id: "guard-tower",
    name: "Guard tower",
    size: 0.5,
    cost: 1300,
    description: "Independent 30-foot tower with guard post. Includes 6 guards.",
    components: [{ componentId: "guard-post", quantity: 1 }],
    staff: [{ role: "guard", count: 6 }],
    monthlyUpkeep: 36,
  },
  {
    id: "inn",
    name: "Inn",
    size: 16,
    cost: 13050,
    description: "Traveler's inn for up to 20 guests and a dozen mounts.",
    components: [
      { componentId: "tavern-basic", quantity: 1 },
      { componentId: "stable-basic", quantity: 2 },
      { componentId: "bedrooms-basic", quantity: 10 },
      { componentId: "kitchen-fancy", quantity: 1 },
      { componentId: "servants-quarters", quantity: 1 },
      { componentId: "storage-basic", quantity: 1 },
    ],
    staff: [
      { role: "cook", count: 2 },
      { role: "groom", count: 2 },
      { role: "servant", count: 2 },
    ],
    monthlyUpkeep: 21,
  },
  {
    id: "inn-dockside",
    name: "Inn, dockside",
    size: 16,
    cost: 12550,
    description: "Inn with a small dock for boating customers.",
    components: [
      { componentId: "tavern-basic", quantity: 1 },
      { componentId: "stable-basic", quantity: 1 },
      { componentId: "dock-basic", quantity: 1 },
      { componentId: "bedrooms-basic", quantity: 10 },
      { componentId: "kitchen-fancy", quantity: 1 },
      { componentId: "servants-quarters", quantity: 1 },
      { componentId: "storage-basic", quantity: 1 },
    ],
    staff: [
      { role: "cook", count: 2 },
      { role: "groom", count: 1 },
      { role: "laborer", count: 2 },
      { role: "servant", count: 2 },
    ],
    monthlyUpkeep: 22.5,
  },
  {
    id: "prison-complex",
    name: "Prison complex",
    size: 13,
    cost: 10500,
    description: "Prison holding up to 60 captives with guard barracks.",
    components: [
      { componentId: "prison-cell", quantity: 10 },
      { componentId: "kitchen-basic", quantity: 2 },
      { componentId: "barracks", quantity: 2 },
      { componentId: "guard-post", quantity: 1 },
      { componentId: "servants-quarters", quantity: 1 },
      { componentId: "torture-chamber", quantity: 1 },
    ],
    staff: [
      { role: "cook", count: 4 },
      { role: "guard", count: 20 },
      { role: "torturer", count: 1 },
    ],
    monthlyUpkeep: 141,
  },
  {
    id: "residential-basic",
    name: "Residential, basic",
    size: 11.5,
    cost: 12000,
    description: "Basic housing for 30 people.",
    components: [
      { componentId: "bedrooms-basic", quantity: 8 },
      { componentId: "kitchen-basic", quantity: 2 },
      { componentId: "dining-hall", quantity: 1 },
      { componentId: "bath-basic", quantity: 1 },
    ],
    staff: [{ role: "cook", count: 2 }],
    monthlyUpkeep: 6,
  },
  {
    id: "residential-fancy",
    name: "Residential, fancy",
    size: 15,
    cost: 66400,
    description: "Fancy housing for 30 people with quality furnishings.",
    components: [
      { componentId: "bedrooms-fancy", quantity: 10 },
      { componentId: "kitchen-fancy", quantity: 1 },
      { componentId: "dining-hall-fancy", quantity: 1 },
      { componentId: "bath-fancy", quantity: 1 },
      { componentId: "servants-quarters", quantity: 1 },
    ],
    staff: [
      { role: "cook", count: 2 },
      { role: "servant", count: 1 },
    ],
    monthlyUpkeep: 9,
  },
  {
    id: "residential-luxury",
    name: "Residential, luxury",
    size: 40,
    cost: 411600,
    description: "Opulent luxury housing for 30 people.",
    components: [
      { componentId: "bedrooms-luxury", quantity: 15 },
      { componentId: "dining-hall-luxury", quantity: 1 },
      { componentId: "kitchen-luxury", quantity: 1 },
      { componentId: "bath-luxury", quantity: 1 },
      { componentId: "servants-quarters", quantity: 4 },
    ],
    staff: [
      { role: "cook", count: 6 },
      { role: "servant", count: 3 },
      { role: "valet", count: 16 },
    ],
    monthlyUpkeep: 123,
  },
  {
    id: "temple",
    name: "Temple",
    size: 5,
    cost: 14900,
    description: "Fancy chapel with religious library and office.",
    components: [
      { componentId: "chapel-fancy", quantity: 1 },
      { componentId: "library-fancy", quantity: 1 },
      { componentId: "study-fancy", quantity: 1 },
      { componentId: "storage-fancy", quantity: 1 },
    ],
    staff: [{ role: "acolyte", count: 1 }],
    monthlyUpkeep: 30,
  },
  {
    id: "wizards-research",
    name: "Wizard's research",
    size: 5,
    cost: 16900,
    description: "Arcane laboratories and library for spell research.",
    components: [
      { componentId: "alchemical-lab-fancy", quantity: 1 },
      { componentId: "library-fancy", quantity: 1 },
      { componentId: "magic-lab-fancy", quantity: 1 },
      { componentId: "study-fancy", quantity: 1 },
      { componentId: "servants-quarters", quantity: 1 },
    ],
    staff: [
      { role: "alchemist", count: 1 },
      { role: "apprentice", count: 1 },
    ],
    monthlyUpkeep: 60,
  },
];

export const CLUSTER_MAP = new Map(
  STRONGHOLD_CLUSTERS.map((c) => [c.id, c]),
);
