// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// Local dev: loaded from web/.env via dotenv.
// Docker build: .env is excluded; placeholder satisfies prisma generate (no DB connection).
const databaseUrl =
  process.env.DATABASE_URL ??
  "postgresql://build:build@localhost:5432/build";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
