import type { NpcFgExportState, NpcFgSpellRow, NpcMediaState } from "./types";

export const DEFAULT_SPELL_ROW = (): NpcFgSpellRow => ({
  level: 0,
  name: "Detect Magic",
  prepared: 1,
  schoolShort: "divination",
  schoolFull: "Divination",
  levelStr: "Brd 0, Clr 0, Drd 0, Sor/Wiz 0",
  castingTime: "1 standard action",
  components: "V, S",
  range: "60 ft.",
  area: "Cone-shaped emanation",
  duration: "Concentration, up to 1 min./level (D)",
  save: "None",
  sr: "No",
  short: "Detects spells and magic items within 60 ft.",
  description:
    "You detect magical auras. The amount of information revealed depends on how long you study a particular area or subject.",
  othertags: "zero; ",
  srNotAllowed: true,
  savetype: "",
});

export const DEFAULT_MEDIA = (): NpcMediaState => ({
  portraitDataUrl: "",
  tokenDataUrl: "",
  picturePath: "",
  tokenPath: "",
  token3DPath: "",
});

export const DEFAULT_NPC_FG_STATE: NpcFgExportState = {
  meta: {
    rootVersion: "5.1",
    rootDataversion: "20260124",
    rootRelease: "9|CoreRPG:7",
  },
  identity: {
    name: "New NPC",
    alignment: "Neutral",
    creatureTypeTag: "Medium humanoid (human)",
    advancement: "By character class",
    organization: "-",
    environment: "Any",
    treasure: "Standard",
    cr: 1,
    levelAdjustment: "+0",
    locked: false,
  },
  defense: {
    ac: "10",
    hp: 4,
    hd: "1d8",
    fort: 0,
    ref: 0,
    will: 0,
    init: 0,
  },
  abilities: {
    str: 10,
    dex: 10,
    con: 10,
    int: 10,
    wis: 10,
    cha: 10,
  },
  offense: {
    atk: "—",
    fullatk: "—",
    babgrp: "+0",
    speed: "30 ft. (6 squares)",
    spaceReach: "5 ft./5 ft.",
    specialattacks: "—",
  },
  senses: "",
  aura: "",
  languages: "Common",
  feats: "",
  skills: "",
  dr: "",
  spellResistance: "",
  immunities: "",
  resistances: "",
  vulnerabilities: "",
  specialqualitiesExtra: "",
  specialqualitiesManual: "",
  useLegacySpecialqualitiesOnly: false,
  specialattacksOverride: "",
  notesFormattedHtml:
    "<p><b>Notes:</b> Stack an archetype + level template (and optional monster templates), then refine fields. Download XML for Fantasy Grounds 3.5.</p>",
  magicalEffectsNotes: "",
  spellcasting: {
    enabled: false,
    mode: "preparation",
    label: "Cleric",
    casterLevel: 1,
    dcAbility: "wisdom",
    dcMisc: 0,
    slots: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
    spells: [],
    spellsetXmlOverride: "",
  },
  spellDisplayMode: "action",
  media: DEFAULT_MEDIA(),
};
